version: '3.8'

services:
  dev:
    container_name: channel_messenger_dev
    image: channel_messenger_dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
    networks:
      - server-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  prod:
    container_name: channel_messenger_prod
    image: channel_messenger_prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: node ./dist/main.js
    ports:
      - 3000:3000
    networks:
      - server-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  server-network:
